apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  params:
  - name: username
    type: string
  steps:
    - name: goodbye
      image: gcr.io/cloud-builders/gcloud:latest@sha256:a31fafb5440cdec7b5adf7550d54187046211701ed93218ba78448a08fb9f551
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"
        echo "some other thing"       
 
