apiVersion: tekton.dev/v1beta1
FROM amd64/ubuntu:18.04
kind: Task
metadata:
  name: gcloud
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.41.0"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: "gcloud"
    tekton.dev/displayName: "gcloud cli"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: |
    The gcloud task to run gcloud-cli commands
    This task is mostly a wrapper.
  params:
  - name: args
    type: array
    description: gcloud CLI arguments to run
    default:
      - help

  steps:
  
  - name: gcloud
    image: "gcr.io/distroless/base-debian12:debug-nonroot@sha256:a302a1643a267feb5e04b2584255402faa5b8c192a6087408605e83d64e82e20"
    command: [gcloud]
    args: ["$(params.args)"]
